### ISSUE TITLE
[QUESTION] Dark/Light mode

### ISSUE THREAD

**Issue by ShowMeYourSkil** [Universumgames/TIDILE#11]
> Question by ShowMeYourSkil

Hey guys,

i was bored and wrote a dark/light color change function in my fork. 
With this function you can change the webinterface from a light mode to a dark mode. 
Would you like to have this feature? I would then open a PR. 
If not, I will simply delete the code again...

See you soon!

**Comment by Universumgames** [comment]
Just create a pull request and I'll look into it...

**Comment by ShowMeYourSkil** [comment]
Ok, cool... I just saw a stupid thing I'm gonna fix.
